const menu = [
  {
    id: 1,
    title: "Hamburguer",
    category: "lanches",
    price: 13.99,
    img: "./images/item-1.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse volutpat lacus velit.  `,
  },
  {
    id: 2,
    title: "Milkshake",
    category: "sorvetes",
    price: 12.99,
    img: "./images/item-2.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis quam nec. `,
  },
  {
    id: 3,
    title: "Açaí",
    category: "sorvetes",
    price: 7.99,
    img: "./images/item-3.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent laoreet ex elit. `,
  },
  {
    id: 4,
    title: "Refrigerante",
    category: "bebidas",
    price: 18.99,
    img: "./images/item-4.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in dolor in.  `,
  },
  {
    id: 5,
    title: "Batata Frita",
    category: "lanches",
    price: 8.99,
    img: "./images/item-5.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget viverra dolor. `,
  },
  {
    id: 6,
    title: "Pizza 1",
    category: "pizzas",
    price: 5.99,
    img: "./images/item-6.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sollicitudin magna. `,
  },
  {
    id: 7,
    title: "Pastel",
    category: "lanches",
    price: 4.99,
    img: "./images/item-7.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eleifend odio eget.  `,
  },
  {
    id: 8,
    title: "Suco",
    category: "bebidas",
    price: 5.99,
    img: "./images/item-8.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tincidunt pulvinar erat. `,
  },
  {
    id: 9,
    title: "Pizza 2",
    category: "pizzas",
    price: 16.99,
    img: "./images/item-9.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla scelerisque magna leo. `,
  },
  {
    id: 10,
    title: "Cachorro-quente",
    category: "lanches",
    price: 8.99,
    img: "./images/item-10.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla scelerisque magna leo. `,
  },
];

export default menu
